meta_product_name: "Museum Around"
meta_title: "Museum Around - La culture à portée de main"
meta_description: "Découvrez toutes les expos et musées autour de vous !"
meta_image: "cover.png" # should exist in `app/assets/images/`
